cmake: Modernize exported CMake config files
COVESA/capicxx-dbus-runtime pull request #11
Opened 2018-10-22 16:05 UTC by neverpanic

The CMake configuration files exported by CommonAPI-DBus require users to add the `${COMMONAPI_DBUS_INCLUDE_DIRS}` variable to their project's include directories. This was done to support building against a build tree of CommonAPI-DBus by generating two different
`CommonAPI-DBusConfig.cmake` files that defined this variable with different values.

This is now no longer necessary since CMake supports the `$<BUILD_INTERFACE>` and `$<INSTALL_INTERFACE>` generator expressions which can be used to make the same distinction with only a single `CommonAPI-DBusConfig.cmake` file.

This also allows users of CommonAPI-DBus to get the required include directories into their build by using
```cmake
target_link_libraries(${target} CommonAPI-DBus)
```
since the exported CommonAPI-DBus CMake target now has the required include directories set as a property. This is much more idiomatic for users of CMake and is thus preferred.

Additionally, the exported target required users to manually find a copy of DBus and link against DBus as well as against CommonAPI-DBus rather than automatically locating the DBus dependency. Modify the target to also do this step automatically so that users of CommonAPI-DBus only
need to care about the CommonAPI-DBus CMake target.

This enables downstream projects that build CommonAPI interface libraries to no longer care about what the CommonAPI-DBus include directories are, which simplifies writing CMake config files for them.

I've locally compiled vSomeIP, CommonAPI, CommonAPI-SomeIP and a test project using CommonAPI-SomeIP to test this. I would have done the same for CommonAPI-DBus, but unfortunately this state of capicxx-dbus-runtime does not compile against my system's DBus headers, so I couldn't test this. Since the change is basically the same as in the other PRs, I don't expect any problems. Additionally, I will perform testing on these changes in an internal project and report if I encounter any problems.

2018-11-01 17:29 UTC, gunnarx commented
Looks like a great change but I'm no expert.  Need @GeniviCommonAPImaintainer  to evaluate and test and merge.

> this state of capicxx-dbus-runtime does not compile against my system's DBus headers

Yes, you might know this but just to confirm, libdbus still needs to be patched to add a few additional functions for optimization in order for the DBus runtime to work.  I suppose it was the reason for the original special cases here -- to point to specific patched version of the library?

* As you say, we might just trust your change works also there, but since it is a bit different in that it requires the patched library, it needs to be tested to be sure.   I suppose it will be brought into an embedded system build (like the meta-ivi baseline) eventually where the patched D-Bus is present.  

* Alternatively, perhaps a container approach could be used to test the compilation with the patched D-Bus installed in the "system" (but in the container).

* Alternatively, there's [this script](https://github.com/gunnarx/build-common-api-cpp-native/blob/master/build-commonapi.sh) which points PKG_CONFIG_PATH to a local directory where the patched D-Bus is identified.  It's a separate copy of libdbus stored locally so not modifying your actual system.  Maybe worth testing if that method still works with your change here.

2018-11-02 00:34 UTC, neverpanic commented
Yeah, as I mentioned, I'm testing this in an internal project to make sure the entire stack keeps working. As of now, I may have found some issues with the CMake I wrote in this patch (the other ones seem fine), so I will submit an updated patch as soon as I find the time.

2019-02-11 15:29 UTC, neverpanic commented
I finally had a few spare cycles to come back to this and am happy to report that the series of patches now works. In systems where autotools are used to compile DBus, users should also apply https://gitlab.freedesktop.org/dbus/dbus/merge_requests/96/, since the DBus CMake configuration may otherwise clobber pkg-config environment variables that could affect cross-compilation.

The upside of this change is that it is now possible to generate fully working CMake config files for interface libraries :)

2023-11-08 17:32 UTC, goncaloalmeida requested changes
please solve the merge conflicts

2023-11-08 17:48 UTC, closed without merging

2023-11-08 17:48 UTC, neverpanic commented
Yeah, that's not happening, I stopped working for BMW almost two years ago, and this PR was already more than three years old when I left. You should probably have reacted sooner, but this is now the problem of the downstream maintainers that keep these patches working in node0. Feel free to ask them for a version without conflicts.